/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spdvi.instafitgram3.gui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import spdvi.instafitgram3.DataAcces.DataAccess;
import spdvi.instafitgram3.dto.User;
import spdvi.instafitgram3.logica.LogicaLogin;

/**
 *
 * @author giari
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(414,315);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPasswordHash = new javax.swing.JPasswordField();
        txtNomUsuari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtRegistrat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtPasswordHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordHashActionPerformed(evt);
            }
        });
        getContentPane().add(txtPasswordHash);
        txtPasswordHash.setBounds(189, 169, 150, 22);

        txtNomUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomUsuariActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomUsuari);
        txtNomUsuari.setBounds(189, 114, 150, 22);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicia sessió");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(172, 51, 70, 16);

        jLabel2.setText("Nom d'usuari");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 117, 85, 16);

        jLabel3.setText("Contrasenya");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 172, 85, 16);

        btnLogin.setText("Inicia");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(267, 224, 72, 23);

        txtRegistrat.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtRegistrat.setText("Registra't");
        txtRegistrat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegistratMouseClicked(evt);
            }
        });
        getContentPane().add(txtRegistrat);
        txtRegistrat.setBounds(75, 224, 85, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomUsuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomUsuariActionPerformed

    private void txtPasswordHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordHashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordHashActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtNomUsuari.getText();
        char[] password = txtPasswordHash.getPassword();
        
        if (LogicaLogin.ComprovarLogin(username, password))
        {
            System.out.println("Hola " + username + "!");
            
            DataAccess da = new DataAccess();
            User user = da.getUserByUsername(username);
            
            if (user.isIsInstructor())
            {
                PaginaPrincipal pp = new PaginaPrincipal(user.getId());
                pp.setVisible(true);
                this.dispose();
            } else
            {
                JDialog dialog = new JDialog(this, "Error a l'iniciar sessió", true);
                dialog.setSize(300, 150);
                dialog.setLocationRelativeTo(this);
                dialog.setLayout(new BorderLayout());

                // Crea el missatge
                JLabel missatge = new JLabel("Aquest usuari no és instructor", javax.swing.SwingConstants.CENTER);

                // Crea el botó
                JButton tancarDialog = new JButton("D'acord");
                tancarDialog.addActionListener(e -> dialog.dispose());

                // Crea un panell per al botó i centra'l a la part inferior
                JPanel botonsPanel = new JPanel();
                botonsPanel.add(tancarDialog);

                // Afegim el missatge a la part central i el panell del botó a la part inferior
                dialog.add(missatge, BorderLayout.CENTER);
                dialog.add(botonsPanel, BorderLayout.SOUTH);

                dialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtRegistratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistratMouseClicked
        // TODO add your handling code here:
        Registrar registrar = new Registrar();
        registrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtRegistratMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNomUsuari;
    private javax.swing.JPasswordField txtPasswordHash;
    private javax.swing.JLabel txtRegistrat;
    // End of variables declaration//GEN-END:variables
}
