/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spdvi.instafitgram3.gui;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import spdvi.instafitgram3.DataAcces.DataAccess;
import spdvi.instafitgram3.dto.Attempt;
import spdvi.instafitgram3.dto.User;

/**
 *
 * @author giari
 */
public class UsuarisIntents extends javax.swing.JFrame {
    
    int filaSeleccionada;
    String userIdSeleccionat;

    /**
     * Creates new form UsuarisIntents
     */
    public UsuarisIntents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuaris");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intents");

        DataAccess da = new DataAccess();
        List<User> userList = da.getUsers();

        Object[][] users = new Object[userList.size()][5];

        for(int i = 0; i < userList.size(); i++)
        {
            User user = userList.get(i);
            users[i][0] = user.getId();
            users[i][1] = user.getNom();
            users[i][2] = user.getEmail();
            users[i][3] = user.getPasswordHash();
            users[i][4] = user.isIsInstructor();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            users,
            new String [] {
                "Id", "Nom", "Email", "Contrasenya", "Instructor"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        List<Attempt> attemptList = da.getAttemptsByUserId(userIdSeleccionat);

        Object[][] attempts = new Object[attemptList.size()][6];

        for(int i = 0; i < attemptList.size(); i++)
        {
            Attempt attempt = attemptList.get(i);
            attempts[i][0] = attempt.getId();
            attempts[i][1] = attempt.getIdUser();
            attempts[i][2] = attempt.getIdExercise();
            attempts[i][3] = attempt.getTimeStampStart();
            attempts[i][4] = attempt.getTimeStampEnd();
            attempts[i][5] = attempt.getVideoFile();
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            attempts,
            new String [] {
                "Id", "Intent", "Exercici", "Start", "End", "Video"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1)
        { // Verifiquem que hi ha una fila seleccionada
            updateTableIntents();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void updateTableIntents() {
        if (filaSeleccionada != -1)
        { // Verifiquem que hi ha una fila seleccionada
            userIdSeleccionat = jTable1.getValueAt(filaSeleccionada, 0).toString();
            
            DefaultTableModel tableModel = new DefaultTableModel();
            
            DataAccess da = new DataAccess();
            List<Attempt> attemptList = da.getAttemptsByUserId(userIdSeleccionat);

            Object[][] attempts = new Object[attemptList.size()][6];

            for(int i = 0; i < attemptList.size(); i++)
            {
                Attempt attempt = attemptList.get(i);
                attempts[i][0] = attempt.getId();
                attempts[i][1] = attempt.getIdUser();
                attempts[i][2] = attempt.getIdExercise();
                attempts[i][3] = attempt.getTimeStampStart();
                attempts[i][4] = attempt.getTimeStampEnd();
                attempts[i][5] = attempt.getVideoFile();
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                attempts,
                new String [] {
                    "Id", "Intent", "Exercici", "Start", "End", "Video"
                }
            ));
            jScrollPane2.setViewportView(jTable2);
            
            if (jScrollPane2.getViewport().getView() != jTable2) {
                jScrollPane2.setViewportView(jTable2); // Actualitzar el JScrollPane per mostrar el jList1 actualitzat
            }
        }
        else
        {
            System.out.println("No hi ha cap fila seleccionada.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarisIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarisIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarisIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarisIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarisIntents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
